server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jaxongir
    username: admin
    password: 123456

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    database: postgresql